### ISSUE TITLE
Move everything to CircleCI

### ISSUE THREAD

**Issue by tpendragon** [samvera/maintenance#16]
- [x] hydra-derivatives
  - [x] [https://github.com/samvera/hydra-derivatives/issues/200](https://github.com/samvera/hydra-derivatives/issues/200)
- [x] questioning_authority
  - [x] [https://github.com/samvera/questioning_authority/pull/222](https://github.com/samvera/questioning_authority/pull/222)
- [x] hydra-head
- [x] browse-everything
  - [x] [https://github.com/samvera/browse-everything/issues/271](https://github.com/samvera/browse-everything/issues/271)
- [x] noid-rails
  - [x] [https://github.com/samvera/noid-rails/pull/89](https://github.com/samvera/noid-rails/pull/89)
- [x] hydra-pcdm
  - [x] [https://github.com/samvera/hydra-pcdm/pull/269](https://github.com/samvera/hydra-pcdm/pull/269)
- [x] active_fedora
- [x] ldp (Trey)
- [x] solrizer
- [x] rubydora
- [x] hydra-role-management
- [x] hydra-works
- [x] hydra-file_characterization
- [x] hydra-editor
- [x] om
- [x] samvera.github.io
- [x] valkyrie

**Comment by jrgriffiniii** [comment]
Blocked by https://github.com/samvera/hydra-derivatives/issues/202
