### ISSUE TITLE
Ensure Components are tested with supported Ruby/Rails versions

### ISSUE THREAD

**Issue by tpendragon** [samvera/maintenance#17]
- [x] hydra-derivatives (blocked by https://github.com/samvera/hydra-derivatives/issues/202)
- [x] questioning_authority
- [x] hydra-head
- [x] browse-everything
- [x] noid-rails
- [x] hydra-pcdm
- [x] active_fedora
- [x] ldp
- [x] solrizer (this might not be updated: please see https://github.com/samvera/solrizer/issues/54#issuecomment-490567210)
- [ ] rubydora
- [x] hydra-role-management
- [x] hydra-works
- [x] hydra-file_characterization
- [x] hydra-editor
- [x] om
- [x] samvera.github.io
- [x] valkyrie

**Comment by jrgriffiniii** [comment]
Referencing the notes from the Core Components Maintenance WG meeting held on 03/01/19, attendees determined that the releases of Ruby and Rails which should be supported are those which are still receiving security updates from the community.  These would be the following releases at this point in time:

Ruby:
- 2.6.3
- 2.5.5
- 2.4.6

Rails:
- 5.2.3
- 5.1.7
- 5.0.7.2
- 4.2.11.1

Given that Hyrax (https://github.com/samvera/hyrax/blob/master/.circleci/config.yml), along with some well-maintained Core Components (https://github.com/samvera/valkyrie/blob/master/.circleci/config.yml), are not testing against Rails 4.2.x releases, I'm going to proceed with just trying to introduce this into the test builds.

**Comment by cjcolvar** [comment]
Is the plan to support rails versions that are receiving "security" or "severe security" updates?  I asked at the partner's meeting and I thought @mark-dce said only to the "security" level and not "severe security".  So that would cut out the 4.2.x series.

**Comment by jrgriffiniii** [comment]
The tests on Valkyrie were failing for 4.2.x releases without pinning to specific releases of the `pg` Gem (https://circleci.com/gh/jrgriffiniii/valkyrie/24), so this will definitely assist with reducing the labor involved in component maintenance.

**Comment by jrgriffiniii** [comment]
https://github.com/samvera/valkyrie/pull/728#issuecomment-491080079 corrects my error, in that both the 5.0.x and 4.2.x series should not be used for testing.
