### ISSUE TITLE
Deprecate Solrizer

### ISSUE THREAD

**Issue by tpendragon** [samvera/maintenance#19]
Solrizer removed from ActiveFedora: https://github.com/samvera/active_fedora/pull/1223
Solrizer dependency removed from ActiveFedora: https://github.com/samvera/active_fedora/pull/1384

Change appropriate documentation. List documentation needed in this ticket.

Deprecate on August 1.

**Comment by mark-dce** [comment]
See https://groups.google.com/forum/#!topic/samvera-tech/T83tGB2Sypo
And https://github.com/samvera/solrizer/pull/55
