### ISSUE TITLE
Deprecate OM

### ISSUE THREAD

**Issue by tpendragon** [samvera/maintenance#22]

**Comment by jrgriffiniii** [comment]
https://github.com/awead/solr_ead uses `om` as a core dependency, and this, in turn, is a dependency of the maturing ArcLight project (https://github.com/sul-dlss/arclight/blob/master/arclight.gemspec#L29).   As the ArcLight community is preparing to undertake a significant number of weeks of development sprints with improvements and new features, I would be very cautious about moving to this to `samvera-deprecated`.

Might it be possible, instead, to put out a call to have this transferred to https://github.com/projectblacklight?

**Comment by jrgriffiniii** [comment]
Following the meeting from earlier today, I have raised the question regarding the future necessity of relying upon `om` for `solr_ead` in https://github.com/awead/solr_ead/issues/26

**Comment by jrgriffiniii** [comment]
The proposal to issue a message to the Samvera community calling for the deprecation of `om` was accepted, and the following message was published to the Samvera Tech. mailing list on 08/05/19 with a proposed deprecation deadline of 09/03/19:

> Hello Everyone, 
> 
> Following the conclusion of the most recent sprint undertaken by the 
> Component Maintenance Working Group [1], a question arose as to 
> whether or not the core component om [2] continues to fulfill the 
> requirements of a Samvera project (specifically, the use requirements 
> [3]).  As some Samvera contributors may be aware, the om Gem is no 
> longer a core dependency of hydra-works [4], neither is it used in 
> hydra-file_characterization, hydra-head, nor active_fedora. 
> 
> However, it was discovered that the Gem remains a dependency for the 
> Gem solr_ead [5], which itself is used by the ArcLight project [6]. 
> In response to this, we would like to please put forth a proposal to 
> deprecate om, but with the added request of looking to please move 
> this Gem to the Project Blacklight GitHub organization [7] (instead of 
> samvera-deprecated). 
> 
> As with previous proposals for deprecation, we welcome any concerns or 
> questions regarding this matter on this thread (or, on Slack in the 
> #component-maintenance Channel).  If there are no objections, we hope 
> to see the deprecation completed by September 3, 2019.
> [1] https://wiki.duraspace.org/pages/viewpage.action?pageId=104569141 
> [2] https://github.com/samvera/om 
> [3] https://samvera.github.io/samvera_labs.html#use-requirements 
> [4] https://github.com/samvera/hydra-works/pull/354 
> [5] https://github.com/awead/solr_ead 
> [6] https://github.com/sul-dlss/arclight/blob/master/arclight.gemspec 
> [7] https://github.com/projectblacklight 

(please see https://groups.google.com/d/msg/samvera-tech/2Ul7fumgJbA/6e87E3WxEQAJ)

**Comment by jrgriffiniii** [comment]
It should be noted here that the `solr_ead` Gem has been deprecated in favor of https://github.com/traject/traject in ArcLight (please see https://github.com/projectblacklight/arclight/pull/677)

**Comment by jrgriffiniii** [comment]
This was completed on 09/27/19.
