### ISSUE TITLE
Delete old waffle labels from core component repos

### ISSUE THREAD

**Issue by mark-dce** [samvera/maintenance#23]
**ISSUE**
Waffle used labels to track what column to display a ticket in, so now we have a bunch of obsolete lablels in all of our core repos.

**ACCEPTANCE**
- [x] Figure out which labels were waffle-specific (created to manage waffle columns)
- [x] Delete corresponding labels from each of the core component repos

**Comment by jrgriffiniii** [comment]
The following labels are immediately identifiable as remaining from Waffle.io:

- groomed
- maintenance-groomed
- maintenance in progress
- maintenance ready
- maintenance review

**Comment by jrgriffiniii** [comment]
These have been removed from all components listed on https://samvera.github.io/core_components.html#core-components-and-product-owners

**Comment by jrgriffiniii** [comment]
The following may have been created by Waffle.io, but they seem to be generic and useful as a means by which to organize issues (they are also used in some cases). I will refrain from removing these:

- in progress
- maintenance
- ready
- review

**Comment by jrgriffiniii** [comment]
There are some labels which I don't recall as being related to Waffle.io, but should perhaps be reviewed (please see two examples: https://github.com/samvera/hydra-works/labels/summer-2015, https://github.com/samvera/active_fedora/labels/fcrepo4). I'm going to scope this for https://github.com/samvera/maintenance/issues/48
