### ISSUE TITLE
Promote `iiif_manifest`

### ISSUE THREAD

**Issue by tpendragon** [samvera/maintenance#24]
Requirements:

- [x] https://github.com/samvera-labs/iiif_manifest/issues/38
- [x] https://github.com/samvera-labs/iiif_manifest/issues/39
- [x] https://github.com/samvera-labs/iiif_manifest/issues/40
- [x] https://github.com/samvera-labs/iiif_manifest/issues/41

**Comment by jrgriffiniii** [comment]
All criteria for promotion have been successfully completed.
