### ISSUE TITLE
Evaluate staleness of hydra-pcdm/hydra-works tickets

### ISSUE THREAD

**Issue by tpendragon** [samvera/maintenance#25]

**Comment by jrgriffiniii** [comment]
https://github.com/samvera/hydra-pcdm/issues/53 doesn't seem unreasonable.  I'm not certain if this should be considered stale, but it seems as if there was a consensus at the time.

**Comment by jrgriffiniii** [comment]
https://github.com/samvera/hydra-pcdm/issues/95 might need to be created for `active_fedora` given that it addresses https://github.com/samvera/active_fedora/blob/master/lib/active_fedora/with_metadata/default_schema.rb#L8

**Comment by jrgriffiniii** [comment]
https://github.com/blancoj/hydra-pcdm/tree/issue_145 needs to be rebased, but https://github.com/samvera/hydra-pcdm/issues/145 still may be a valid refactor proposal.

**Comment by jrgriffiniii** [comment]
https://github.com/samvera/hydra-pcdm/issues/177 also needs to be created for `active_fedora`.

**Comment by jrgriffiniii** [comment]
https://github.com/samvera/hydra-pcdm/issues/184 needs to be created for `hydra-works` or `hydra-file_characterization`

**Comment by jrgriffiniii** [comment]
https://github.com/duraspace/pcdm/pull/4/files#r31881404 was merged, so https://github.com/samvera/hydra-pcdm/issues/217 still looks to be valid.

**Comment by jrgriffiniii** [comment]
My suspicion is that https://github.com/samvera/hydra-pcdm/issues/245 is strictly concerned with Hyrax behavior, but I've enquired within the #hyrax Slack Channel in order to confirm that this is indeed the case.

**Comment by jrgriffiniii** [comment]
https://github.com/samvera/hydra-pcdm/issues/266 might be unnecessary, as the coverage is currently reported as being at 99%: https://coveralls.io/github/samvera/hydra-pcdm

**Comment by jrgriffiniii** [comment]
https://github.com/samvera/hydra-works/issues/315 seems to have had a solution with https://github.com/samvera/hydra-works/pull/317, but it was closed without any explanation.

**Comment by jrgriffiniii** [comment]
@mark-dce has volunteered to review the issues created for `hydra-works` in response to this, and will delete or confirm the importance of these.
