### ISSUE TITLE
Ruby 3.0 support in core components

### ISSUE THREAD

**Issue by cjcolvar** [samvera/maintenance#64]
Evaluate, test, and add support for ruby 3.0 to each of the core components.
- [ ] active_fedora
- [ ] browse-everything
- [ ] hydra-derivatives
- [ ] hydra-editor
- [ ] hydra-file_characterization
- [ ] hydra-head
- [ ] hydra-pcdm
- [ ] hydra-role-management
- [ ] hydra-works
- [ ] iiif_manifest
- [ ] ldp
- [ ] noid-rails
- [ ] questioning_authority
- [ ] rubydora
- [ ] valkyrie

**Comment by jrgriffiniii** [comment]
Deprecated by https://github.com/samvera/maintenance/issues/77
