### ISSUE TITLE
Audit the structure of GitHub Teams for the samvera Organization

### ISSUE THREAD

**Issue by jrgriffiniii** [samvera/maintenance#82]
The following Teams currently exist for `samvera`:

- [ ]  [Admins](https://github.com/orgs/samvera/teams/admins)
- [ ]  [Contributors](https://github.com/orgs/samvera/teams/contributors)
- [ ]  [Hyku](https://github.com/orgs/samvera/teams/hyku)

**Comment by jrgriffiniii** [comment]
My proposal would be that one please restructure these into the following:

- [ ]  admins (Members of the community with executive privileges for repositories and the `samvera` Organization on GitHub)
- [ ]  contributors (Members of the community with completed iCLA's)
- [ ]  hyku (Contributors to Hyku - perhaps this is a sub-team of `hyrax`?)
- [ ]  hyrax (Contributors to Hyrax)
- [ ]  avalon (Contributors to the Avalon Media System)
- [ ]  maintainers (Members of the Component Maintenance Interest Group)
- [ ]  partners (Representatives from Samvera Partner organizations)
- [ ]  steering (Members elected to serve on Samvera Steering)

Perhaps the following should also be available, however I am uncertain as to the status of these solutions:
- [ ] curate (Members involved in providing legacy support for this solution)
- [ ] hypatia (Members involved in providing legacy support for this solution)
- [ ] sufia (Members involved in providing legacy support for this solution)

**Comment by hackartisan** [comment]
It sounds like some clean up is definitely in order.

It would be helpful to define the use cases for the teams. Maybe we could reduce maintenance a lot here by eliminating most of them. Are they mostly so people have a group to tag for PR review? If so it may be that a message slack serves that purpose pretty well if not better. Is there another use for them?

**Comment by jrgriffiniii** [comment]
- `contributors` will no longer be required to have iCLAs, but will be in place for those committing directly to branches and reviewing/merging pull requests
- `hyrax` is really unnecessary, as `contributors` would have identical privileges

**Comment by jrgriffiniii** [comment]
The secret teams have now been deleted from the Samvera Organization.

**Comment by jrgriffiniii** [comment]
https://github.com/orgs/samvera/teams/hyku/teams seems to have been actively used, and hence, @jrgriffiniii will contact the members before requesting to delete this Team.

**Comment by jrgriffiniii** [comment]
Currently, the structure of the GitHub Teams now resembles the following:

- [ ]  admins (Members of the community with executive privileges for repositories and the `samvera` Organization on GitHub)
- [ ]  contributors (Members of the community with completed iCLA's)
- [ ]  Hyku (Contributors to Hyku - perhaps this is a sub-team of `hyrax`?)
- [ ]  maintainers (Members of the Component Maintenance Interest Group)

**Comment by jrgriffiniii** [comment]
This should be resolved by what was undertaken in support for #83
